version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    volumes:
      - ${PWD}/kafka/data:/var/lib/zookeeper/data
      - ${PWD}/kafka:/var/lib/zookeeper/log
    ports:
      - "2181:2181"
    networks:
      - kafkazoo

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$THIS_HOST_ADRESS:9092
    networks:
      - kafkazoo
networks:
  kafkazoo:
    driver: bridge

#  kafka-topics.sh --bootstrap-server localhost:9092 --list
#  kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic test3
